## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: GitHub Issues
    url: https://github.com/your-username/agentic-captcha-solver/issues
    about: For questions and discussions, please create an issue in the repository.